Feat/pm4 9/display reservations
pm4-parkship/parkship pull request #43
Opened 2023-04-27 20:50 UTC by chrewbroccoli

## Description

---

## Issues

---

## Demo

2023-04-28 08:21 UTC, Edelmetall commented
Bitte noch zuerst einen Rebase machen, es werden Änderungen gezeigt, die nicht von dir kommen. 
Bsp StandaloneApplication wird als neue Klasse angezeigt.

2023-04-28 08:26 UTC, Edelmetall commented
@chrewbroccoli Frage, hast du deinen Feature branche vom main oder von staging gezogen? 

Es sieht so aus, als hättest du ihn vom main gezogen.
Problem ist, alle Änderungen vom Sprint 3 wurden Squashed und in den Main übernommen. Wenn du jetzt deinen feature Branche vom Main ziehst, und deine Änderungen in den Staging mergen willst, stimmt die git history nicht überein, und es gibt inkonsistenzen in der history und auch beim mergen 
(Siehe Änderungen die nicht du erstellt hast, und trotzdem als Änderung angezeigt wird.)

2023-04-30 20:49 UTC, chrewbroccoli commented
> @chrewbroccoli Frage, hast du deinen Feature branche vom main oder von staging gezogen?
> 
> Es sieht so aus, als hättest du ihn vom main gezogen. Problem ist, alle Änderungen vom Sprint 3 wurden Squashed und in den Main übernommen. Wenn du jetzt deinen feature Branche vom Main ziehst, und deine Änderungen in den Staging mergen willst, stimmt die git history nicht überein, und es gibt inkonsistenzen in der history und auch beim mergen (Siehe Änderungen die nicht du erstellt hast, und trotzdem als Änderung angezeigt wird.)

Habe nun den staging branch in den feature branch gemerged.

2023-05-01 18:05 UTC, lauraBoll requested changes

2023-05-01 18:05 UTC, lauraBoll commented on backend/src/main/java/ch/zhaw/parkship/reservation/ReservationService.java
> +            throw new Exception("User not found");
Bitte custom exceptions verwenden, die von der Klasse BaseException erben.

2023-05-01 18:05 UTC, lauraBoll commented on backend/src/main/java/ch/zhaw/parkship/reservation/ReservationController.java
> +          @PathVariable Long userId, @RequestParam ("from") Optional<LocalDate> from, @RequestParam ("to") Optional<LocalDate> to) throws Exception {
Wozu genau ist das mit den from/to Daten nötig? Das findet man doch alles in der Datenbank und muss sie nicht beim Frontend abfragen? Oder versteh ich das Ticket falsch? Müsste man nicht eher einfach irgendwie zwischen aktuellen und vergangenen Reaervationen unterscheiden können?

2023-05-01 18:05 UTC, lauraBoll commented on backend/src/main/java/ch/zhaw/parkship/reservation/ReservationController.java
> +          @PathVariable Long userId, @RequestParam ("from") Optional<LocalDate> from, @RequestParam ("to") Optional<LocalDate> to) throws Exception {
Die userId ist hier nicht nötig. Mithilfe de AutheticationPrincipals weiss man bereits, welcher User gerade eingeloggt ist und muss keine IDs abfragen beim Frontend. Siehe z.B. bei getUser im UserController

2023-05-01 18:34 UTC, SandroGuerotto commented on backend/src/main/java/ch/zhaw/parkship/reservation/ReservationController.java
> +          @PathVariable Long userId, @RequestParam ("from") Optional<LocalDate> from, @RequestParam ("to") Optional<LocalDate> to) throws Exception {
@lauraBoll habe mit Christoph so besprochen, dass das Frontend from und to mitgeben kann, damit nicht immer alles geladen wird. zB kann 1 Woche in die Vergangenheit und alle in die Zukunft geladen werden

2023-05-01 18:36 UTC, chrewbroccoli commented on backend/src/main/java/ch/zhaw/parkship/reservation/ReservationService.java
> +            throw new Exception("User not found");
okay, also die fehlermeldung erübrigt sich eigentlich, wenn das mit den authentication principles implementiert ist.

2023-05-01 18:37 UTC, chrewbroccoli commented on backend/src/main/java/ch/zhaw/parkship/reservation/ReservationController.java
> +          @PathVariable Long userId, @RequestParam ("from") Optional<LocalDate> from, @RequestParam ("to") Optional<LocalDate> to) throws Exception {
ich werde das noch anpassen und die userid entfernen.

2023-05-01 22:46 UTC, chrewbroccoli commented
@Edelmetall @lauraBoll 
habe die anpassungen nun gemacht.

2023-05-02 15:14 UTC, Edelmetall commented on backend/src/main/java/ch/zhaw/parkship/reservation/ReservationRepository.java
> +            //"SELECT r FROM ReservationEntity r WHERE r.tenant.id = ?1 AND r.from > ?2 AND r.to < ?3 ORDER BY r.from"
!

2023-05-12 10:09 UTC, merged